Added the FuckingApp with revolver. Doesn't finish starting because something something Akka something something NoClassDefFoundError something something fuck this, but revolver works as expected.